const SET_FILTER = 'SET_FILTER';
const GET_PRODUCTS = 'GET_LISTS';
const GET_PRODUCTS_SUCCESS = 'GET_LIST_SUCCESS';
const GET_PRODUCTS_FAIL = 'GET_LIST_FAIL';

export { SET_FILTER, GET_PRODUCTS, GET_PRODUCTS_SUCCESS, GET_PRODUCTS_FAIL};
